import {useEffect,useState} from 'react';import {useServices} from './services/context';import {money} from './utils/money';import DataTable from './components/DataTable';import ResourceForm from './components/ResourceForm';import StatusMessage from './components/StatusMessage';import ConfirmDialog from './components/ConfirmDialog';
const titles={categories:'Категорії',transactions:'Доходи та витрати',budgets:'Місячні бюджети'};
export default function ResourcePage({resource}){
 const {api}=useServices();const [formVersion,setFormVersion]=useState(0);const [rows,setRows]=useState([]),[cats,setCats]=useState([]),[edit,setEdit]=useState(null),[remove,setRemove]=useState(null),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[message,setMessage]=useState('');
 async function load(){setLoading(true);setError('');try{const [r,c]=await Promise.all([api.list(resource),resource==='categories'?Promise.resolve([]):api.list('categories')]);setRows(r);setCats(c);}catch(e){setError(e.message);}finally{setLoading(false);}}
 useEffect(()=>{load();},[resource,api]);
 async function save(data,id){setBusy(true);try{await api.save(resource,data,id);setEdit(null);setFormVersion(v=>v+1);setMessage('Запис збережено.');await load();}finally{setBusy(false);}}
 async function deletion(){setBusy(true);try{await api.remove(resource,remove.id);if(edit?.id===remove.id)setEdit(null);setRemove(null);setMessage('Запис видалено.');await load();}catch(e){setRemove(null);setError(e.message);}finally{setBusy(false);}}
 const name=id=>cats.find(c=>c.id===id)?.name||`Категорія №${id}`;
 const columns=resource==='categories'?[{key:'name',label:'Назва'}]:resource==='budgets'?[{key:'month',label:'Місяць'},{key:'categoryId',label:'Категорія',render:r=>name(r.categoryId)},{key:'limitCents',label:'Ліміт',render:r=>money(r.limitCents)}]:[{key:'occurredOn',label:'Дата'},{key:'kind',label:'Тип',render:r=>r.kind==='income'?'Дохід':'Витрата'},{key:'categoryId',label:'Категорія',render:r=>name(r.categoryId)},{key:'amountCents',label:'Сума',render:r=>money(r.amountCents)},{key:'note',label:'Примітка'}];
 return <><div className="page-heading"><h1>{titles[resource]}</h1><p>Створюйте, переглядайте й оновлюйте записи.</p></div><StatusMessage loading={loading} error={error} message={message} onRetry={load}/><div className="workspace"><ResourceForm key={formVersion} resource={resource} categories={cats} row={edit} busy={busy} onSave={save} onCancel={()=>setEdit(null)}/><section className="panel" aria-label="Список записів">{!loading&&!error&&<DataTable rows={rows} columns={columns} busy={busy} onEdit={setEdit} onDelete={setRemove}/>}</section></div><ConfirmDialog row={remove} busy={busy} onCancel={()=>setRemove(null)} onConfirm={deletion}/></>;
}
